package:
  name: psdaq-control-minimal
  version: 3.3.14

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: 3.3.14
  patches:
    - setup.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install ./psdaq -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - p4p
    - psalg
    - psana
    - transitions
